import { Type } from "@google/genai";
import { ai } from './common';
import { generateContentWithRetry as executeRequest } from '@/utils/apiUtils';
import { safeJsonParse } from '@/utils/jsonUtils';
import type { InternalContact } from '@/types';

type HeaderMap = { [key in keyof Partial<InternalContact>]: string | null };

/**
 * Uses AI to map custom headers from an imported file to the standard InternalContact schema.
 * @param headers - An array of header strings from the user's file.
 * @returns A promise that resolves to a map where keys are schema fields and values are the corresponding user headers.
 */
export const mapHeadersToSchema = async (headers: string[]): Promise<HeaderMap> => {
    const prompt = `You are a data mapping specialist. Your task is to map an array of user-defined column headers to our application's standard schema for a distributor contact.

Our standard schema fields are: "name", "email", "phone", "company", "country", "address".

Here are the headers from the user's uploaded file:
${JSON.stringify(headers)}

**Instructions:**
1.  Analyze the user's headers and find the best match for each of our standard schema fields.
2.  The matching is flexible. "Full Name" or "Contact Person" should map to "name". "Depot Location" or "Site Address" should map to "address".
3.  Your output MUST be a single JSON object. The keys of the object MUST be our standard schema fields.
4.  The values of the object MUST be the corresponding header string from the user's file.
5.  If you cannot find a confident match for one of our fields, the value for that key MUST be \`null\`.

**Example Output:**
If user headers are ["Contact", "Email Address", "Branch", "Location"], your output should be:
{
  "name": "Contact",
  "email": "Email Address",
  "phone": null,
  "company": "Branch",
  "country": null,
  "address": "Location"
}
`;

    const response = await executeRequest(ai, {
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
            responseMimeType: "application/json",
        }
    });

    return safeJsonParse<HeaderMap>(response.text, {});
};

/**
 * Processes raw data from an imported file using a header map to create standardized InternalContact objects.
 * @param rawData - An array of objects from the XLSX parser.
 * @param headerMap - The map generated by mapHeadersToSchema.
 * @returns An array of partial InternalContact objects, ready for database insertion.
 */
export const processImportedContacts = (rawData: any[], headerMap: HeaderMap): Partial<Omit<InternalContact, 'id'>>[] => {
    const processedContacts: Partial<Omit<InternalContact, 'id'>>[] = [];

    const schemaKeys = Object.keys(headerMap) as (keyof HeaderMap)[];

    for (const row of rawData) {
        const newContact: Partial<Omit<InternalContact, 'id'>> = {};
        let hasData = false;

        for (const key of schemaKeys) {
            const userHeader = headerMap[key];
            if (userHeader && row[userHeader]) {
                newContact[key] = String(row[userHeader]).trim();
                hasData = true;
            }
        }
        
        // Only add contacts that have at least some data and a name or email
        if (hasData && (newContact.name || newContact.email)) {
            processedContacts.push(newContact);
        }
    }

    return processedContacts;
};